set_property PACKAGE_PIN AB6 [get_ports {SSRon[7]}]
set_property PACKAGE_PIN AB7 [get_ports {SSRon[6]}]
set_property PACKAGE_PIN T6 [get_ports {SSRon[5]}]
set_property PACKAGE_PIN R6 [get_ports {SSRon[4]}]
set_property PACKAGE_PIN AB8 [get_ports {SSRon[3]}]
set_property PACKAGE_PIN AA8 [get_ports {SSRon[2]}]
set_property PACKAGE_PIN AA6 [get_ports {SSRon[1]}]
set_property PACKAGE_PIN Y6 [get_ports {SSRon[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSRon[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSRon[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSRon[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSRon[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSRon[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSRon[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSRon[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSRon[0]}]
set_property PACKAGE_PIN Y21 [get_ports PWM1]
set_property PACKAGE_PIN AA21 [get_ports PWM2]
set_property IOSTANDARD LVCMOS33 [get_ports PWM1]
set_property IOSTANDARD LVCMOS33 [get_ports PWM2]

set_property IOSTANDARD LVCMOS33 [get_ports sys_clock]

set_property PACKAGE_PIN H14 [get_ports PWM1]
set_property PACKAGE_PIN G13 [get_ports PWM2]
